### ISSUE TITLE
Upgrading to IPython 4.0

### ISSUE THREAD

**Issue by chrisjsewell** [chrisjsewell/PyGauss#36]
particularly because of chemview
Have to use Ipython 3.2.1 and Spyder 2.3.5.2 for now

**Comment by gabrielelanaro** [comment]
@chrisjsewell  I can deal with the chemview part :)

**Comment by chrisjsewell** [comment]
Hey thanks, here's the traceback:

Traceback (most recent call last):

  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName

    addr.filename, addr.module)

  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath

    return self.importFromDir(dir_path, fqname)

  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir

    mod = load_module(part_fqname, fh, filename, desc)

  File "/home/travis/build/chrisjsewell/PyGauss/helper_funcs.py", line 8, in <module>

    import pygauss as pg

  File "/home/travis/build/chrisjsewell/PyGauss/pygauss/__init__.py", line 32, in <module>

    from .molecule import Molecule

  File "/home/travis/build/chrisjsewell/PyGauss/pygauss/molecule.py", line 86, in <module>

    from .chemview_patch.viewer import MolecularViewer

  File "/home/travis/build/chrisjsewell/PyGauss/pygauss/chemview_patch/viewer.py", line 10, in <module>

    from chemview.widget import RepresentationViewer, TrajectoryControls

  File "/home/travis/miniconda/lib/python2.7/site-packages/chemview/__init__.py", line 2, in <module>

    from .widget import RepresentationViewer

  File "/home/travis/miniconda/lib/python2.7/site-packages/chemview/widget.py", line 8, in <module>

    from IPython.html.widgets import DOMWidget

ImportError: cannot import name DOMWidget
